# Shell variables
# Generated by 'wal'
wallpaper="__ANOMALE_HOME__/Pictures/wallpaper/wallpaper_2.png"

# Special
background='#20200e'
foreground='#c7c7c2'
cursor='#c7c7c2'

# Colors
color0='#20200e'
color1='#a5a87c'
color2='#a4a98a'
color3='#a5a996'
color4='#a5a9a0'
color5='#a7a9a8'
color6='#a2a2aa'
color7='#c7c7c2'
color8='#72725d'
color9='#a5a87c'
color10='#a4a98a'
color11='#a5a996'
color12='#a5a9a0'
color13='#a7a9a8'
color14='#a2a2aa'
color15='#c7c7c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
