--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="__ANOMALE_HOME__/Pictures/wallpaper/wallpaper_2.png"

-- Special
background="#20200e"
foreground="#c7c7c2"
cursor="#c7c7c2"

-- Colors
color0="#20200e"
color1="#a5a87c"
color2="#a4a98a"
color3="#a5a996"
color4="#a5a9a0"
color5="#a7a9a8"
color6="#a2a2aa"
color7="#c7c7c2"
color8="#72725d"
color9="#a5a87c"
color10="#a4a98a"
color11="#a5a996"
color12="#a5a9a0"
color13="#a7a9a8"
color14="#a2a2aa"
color15="#c7c7c2"
