foreground         #c7c7c2
background         #20200e
background_opacity 1.0
cursor             #c7c7c2

active_tab_foreground     #20200e
active_tab_background     #c7c7c2
inactive_tab_foreground   #c7c7c2
inactive_tab_background   #20200e

active_border_color   #c7c7c2
inactive_border_color #20200e
bell_border_color     #a5a87c

color0       #20200e
color8       #72725d
color1       #a5a87c
color9       #a5a87c
color2       #a4a98a
color10      #a4a98a
color3       #a5a996
color11      #a5a996
color4       #a5a9a0
color12      #a5a9a0
color5       #a7a9a8
color13      #a7a9a8
color6       #a2a2aa
color14      #a2a2aa
color7       #c7c7c2
color15      #c7c7c2
