[colors]
background = '#20200e8e'
black = '#20200e'
blue = '#a5a87c'
cursor = '#c7c7c2'
cyan = '#a4a98a'
foreground = '#c7c7c2'
green = '#a5a996'
magenta = '#a5a9a0'
red = '#a7a9a8'
tabs = '#c7c7c2'
tabs-active = '#a2a2aa'
white = '#c7c7c2'
yellow = '#c7c7c2'
dim-black = '#20200e8e'
dim-blue = '#a5a87c8e'
dim-cyan = '#a4a98a8e'
dim-foreground = '#c7c7c28e'
dim-green = '#a5a9968e'
dim-magenta = '#a5a9a08e'
dim-red = '#a7a9a88e'
dim-white = '#a2a2aa8e'
dim-yellow = '#c7c7c28e'
light-black = '#a5a87c'
light-blue = '#a4a98a'
light-cyan = '#a5a996'
light-foreground = '#a5a9a0'
light-green = '#a7a9a8'
light-magenta = '#a2a2aa'
light-red = '#c7c7c2'
light-white = '#a5a87c'
light-yellow = '#a4a98a'
