# pywal theme for ghostty

background = 20200e
foreground = c7c7c2
cursor-color = c7c7c2
selection-background = c7c7c2
selection-foreground = 20200e

palette = 0=#20200e
palette = 1=#a5a87c
palette = 2=#a4a98a
palette = 3=#a5a996
palette = 4=#a5a9a0
palette = 5=#a7a9a8
palette = 6=#a2a2aa
palette = 7=#c7c7c2
palette = 8=#72725d
palette = 9=#a5a87c
palette = 10=#a4a98a
palette = 11=#a5a996
palette = 12=#a5a9a0
palette = 13=#a7a9a8
palette = 14=#a2a2aa
palette = 15=#c7c7c2
