# MangoWC Pywal Template
# ----------------------

# Borders (Your Request)
focuscolor=0xa2a2aaff
bordercolor=0x20200eff

# General
rootcolor=0x20200eff
urgentcolor=0xa5a87cff

# Window States
maximizescreencolor=0xa7a9a8ff
scratchpadcolor=0xa5a9a0ff
globalcolor=0xc7c7c2ff
overlaycolor=0xa5a996ff

# Effects
shadowscolor=0x20200e70
