[General]
background=background.jpg
rect_color=#20200e
border_color=#a2a2aa
text_color=#a2a2aa
input_bg_color=#20200e
input_border_color=#a2a2aa
input_hover_color=#20200e
input_focus_color=#a2a2aa
input_pressed_color=#20200e
font_family=0xProto Nerd Font


