[General]
background=background.jpg
rect_color=#211c0e
border_color=#69aa50
text_color=#69aa50
input_bg_color=#211c0e
input_border_color=#69aa50
input_hover_color=#211c0e
input_focus_color=#69aa50
input_pressed_color=#211c0e
font_family=0xProto Nerd Font


