# Anomale Bar Configuration
# for individual monitor/bar configuration, anomale is designed to prioritize .conf files that are named after your active monitors. 
# (example: eDP-1.conf is prioritized over config.conf) 
# (example2: if you have both DP-1.conf and DP-2.conf. The bars can be configured uniquely on each monitor)

# Bar Appearance
bar_height = 20
bar_color = pywal_color0
font_family = 0xProto Nerd Font
#font_family = Monospace
#vert align variables change the vertical positioning of text in the bar or the tag bullets, as some fonts position these differently, this may need tweaking
font_vert_align = 2
bullet_vert_align = 0
font_size = 16
font_color = pywal_color6
max_width = 800
alignment = center
# pywal variable set to true makes anomale look to pywal templates for colors, enabling the use of "pywal_color#" to set variables that expect colors.
pywal = true
bar_opacity = 100
border_color = pywal_color6
border = 2
tleft_corner = 0
tright_corner = 0
bleft_corner = 0
bright_corner = 0

# you can use your scroll wheel over the volume module in order to adjust your volume. This affects that speed.
# alternatively, you can click the module and arrows will appear that you can use to adjust volume as well (they disappear after a few seconds of no adjustments)
volume_scroll_speed=1

# Module Layout. Multiple modules allowed per position, comma separated. 
# module options are "tags, clock, volume, battery, resources:cpu, resources:gpu, resources:mem"
left = tags
center = clock
right = volume
# you can change the specific font of the degrees symbol on the resource modules. Monospaced fonts tend to make that symbol take up too much space, and it looks bad.
degree_symbol_font = sans
clock_format = "%I:%M %p"

# Only top and bottom positions supported currently.
position=top
edge_distance=10

shadow_size = 0
shadow_blur = 0
shadow_offset_x = 4
shadow_offset_y = 4
shadow_color = pywal_color0
shadow_opacity = 0.3


#EXECS
exec = mmsg dispatch reload_config
