search_width=350
background_color=pywal_color0
background_opacity=1
border_color=pywal_color6
border_width=2
border_radius=0
text_color=pywal_color6
font_family=0xProto Nerd Font
font_size=14.0
selection_color=pywal_color6
selection_text_color=pywal_color1
highlight_color=pywal_color2
highlight_text_color=pywal_color0
search_background_opacity=1

#apps launcher settings
apps_opacity=0.7

# Power Menu
power_3=Reboot:systemctl reboot
power_1=Shutdown:systemctl poweroff
power_2=Logout:mmsg -d quit
power_opacity=0.7

# Wallpaper Selector
# This path is searched to display options in your wallpaper selector popup
wallpapers_path=~/Pictures/wallpaper/
wallpapers_thumb_size=200
# The [[w]] placeholder is used where you would like anomale to insert the path to the selected image into your wallpaper set/theme application
wallpapers_command=wal --backend colorz --contrast 2.0 --cols16 foxify-lighten -i [[w]] && mmsg dispatch reload_config
# makes sure your last set wallpaper is applied at boot
use_last_wall=true
#opacity of wallpaper menu (use 1.0 if blur is off for dropshadow)
wallpapers_opacity=1
