[General]
background=background.jpg
rect_color={color0}
border_color={color6}
text_color={color6}
input_bg_color={color0}
input_border_color={color6}
input_hover_color={color6}
input_focus_color={color6}
input_pressed_color={color0}
font_family=0xProto Nerd Font

