# Anomale Bar Configuration

# Bar Appearance
bar_height = 24
bar_color = #000000ff
font_family = monospace
font_size = 12.0
font_color = #ffffffff

# Module Layout (comma separated)
left = resources:cpu, resources:gpu, resources:mem, resources:swap, tags
center = clock
right = volume

clock_format = "%I:%M %p"
