search_width=350
background_color=pywal_color0
background_opacity=0.6
# apps_background_color=pywal_color0
# apps_opacity=0.4
# search_background_color=pywal_color1
# search_background_opacity=0.9
border_color=pywal_color6
border_width=2
border_radius=0
text_color=pywal_color6
font_family=monospace
font_size=14.0
selection_color=pywal_color6
selection_text_color=pywal_color1
highlight_color=pywal_color2
highlight_text_color=pywal_color0

# Power Menu
power_3=Reboot:systemctl reboot
power_1=Shutdown:systemctl poweroff
power_2=Logout:mmsg dispatch quit

# Wallpaper Selector
wallpapers_path=~/Pictures/wallpaper/
wallpapers_thumb_size=200
wallpapers_command=wal --backend haishoku -i [[w]] && pywalfox update; mmsg dispatch reload_config
use_last_wall=true
